spring:
  data:
    cassandra:
      keyspace-name: springcassendra
      contact-points: localhost
      port: 9042
      local-datacenter: datacenter1
      schema-action: create_if_not_exists
      connection:
         connect-timeout: PT10S
         init-query-timeout: PT20S
      request:
         timeout: PT10S
  main:
    allow-bean-definition-overriding: true
    
  application:
    name: CHANGED-PASSWORD-SERVICE
    
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      hostame: localhost
    
    
logging.level.com.datastax.driver.core.QueryLogger.NORMAL: DEBUG
logging.level.com.datastax.driver.core.QueryLogger.SLOW: TRACE


logging:
  level:
    org:
      springframework:
        data:
          cassandra:
            core:
              cql:
                CqlTemplate: DEBUG
